version: '3'

services:
  helloworld:
    container_name: helloworld
    image: nginx:1.24.0-alpine-slim
    networks:
      - my_network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
