version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #  - ./html:/usr/share/nginx/html
    depends_on: 
      - krakend
    networks:
      - my_network
    
  
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5.1
    volumes:
      - ./krakend/krakend.yaml:etc/krakend/krakend.yaml
    ports:
      - "8080:8080"
    networks:
      - my_network
    

networks:
  my_network:
    driver: bridge
