version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - backend
  
  frotend:
    container_name: vue_frotend
    image: node:21  
    working_dir: /app
    volumes:
      - ./assessment-ui:/app
    ports:
      - 8080:8080
    restart: unless-stopped
    command: npm install sass vite @vitejs/plugin-vue --save-dev && npm run dev
    networks:
      - backend

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    ports:
      - "1212:1212"
    command: ["run","-d","-c", "/etc/krakend/krakend.json"]
    restart: unless-stopped 
    networks:
      - backend
  
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: unless-stopped 
    ports:
      - "8081:8081"
    volumes:
      - ./api/account.yaml:/swagger/account.yaml
    environment:
      SWAGGER_JSON: /swagger/account.yaml
    networks:
      - backend

networks:
  backend:
    driver: bridge
