version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5
    volumes:
      - ./krakend/krakend.yaml:/etc/krakend/krakend.yaml
    ports:
      - "8090:8090"
    restart: unless-stopped 
    networks:
      - backend
  
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: unless-stopped 
    ports:
      - "8080:8080"
    volumes:
      - ./api/account.yaml:/swagger/account.yaml
    environment:
      SWAGGER_JSON: /swagger/account.yaml
    networks:
      - backend

networks:
  backend:
    driver: bridge
