version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5.1
    ports:
      - "8080:8080"
    networks:
      - backend
  
  swager:
    container_name: swagger
    image: swaggerapi/swagger-ui
      - "1212:1212"
    volumes:
      - ./api/account.yaml:/swagger.yaml:ro
    environment:
      SWAGGER_JSON: /swagger.yaml
    networks:
      - backend

networks:
  backend:
    driver: bridge

