version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "801:801"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5.1
    ports:
      - "8080:8080"
    networks:
      - backend
  
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - "1212:8080"
    volumes:
      - ./api/account.yaml:/snigger/api/account.yaml
    environment:
      SWAGGER_JSON: /snigger/api/account.yaml
    networks:
      - backend

networks:
  backend:
    driver: bridge
