version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on: 
      - krakend
    networks:
      - backend
    
  
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5.1
    volumes:
      - ./api/account.yaml:/etc/krakend/krakend.yaml
    ports:
      - "8080:8080"
    networks:
      - backend
    

networks:
  backend:
    driver: bridge

