version: '3'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.24.0-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - krakend
    networks:
      - backend
    

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.5.1
    ports:
      - "8080:8080"
    networks:
      - backend
  
  swager:
    container_name: swager
    image: swaggerapi/swagger-ui:v5.11.8
    ports:
      - "1212:1212"
    environment:
      - SWAGGER_JSON=/api/swagger.json
    volumes:
      - ./api/account.yaml:/api/account.yaml:ro
    networks:
      - backend
    depends_on:
      - nginx

networks:
  backend:
    driver: bridge

